### PR TITLE
Fix parser error when OFX contains a self closed tag

### PR DESCRIPTION
**Pull request by leandrost**
https://trello.com/c/5k9gHMbU/945-5-0-corrigir-tratamento-da-tag-branchid-no-fixofx

### CODE REVIEW

**Comment by leandrost** [comment]
@rtopitt @wpolicarpo @vagnerzampieri review ???

**Comment by vagnerzampieri** [comment]
:+1:

**Comment by rtopitt** [comment]
:+1:

**Comment by tauil** [comment]
:+1: Só pra matar a saudade! :heart:

**Comment by leandrost** [comment]
tauil-quefase

**Comment by tauil** [comment]
image

**Comment by leandrost** [comment]
hahahaha válido

**Pull request merged**
